(in-package :z80)

(defun test-register-set/read ()
  (let ((c (make-instance 'cpu)))
    (setf (slot-value c 'af) #b1111111100000010)
    (let ((init-list (list (reg-a c) (reg-f c) (reg-af c))))
      (setf (reg-a c) 15)
      (setf (reg-f c) 9)
      (setf (reg-a c) 15)
      (setf (reg-f c) 9)
      (setf (reg-a c) 99)
      (setf (reg-f c) 123)
      (setf (reg-af c) 65535)
      (list init-list (list (reg-a c) (reg-f c) (reg-af c))))))
